<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="style/main3.css" />
		<title>Редактирование таблицы на Python, JavaScript</title>
		<meta name="ROBOTS" content="NOINDEX,NOFOLLOW,NOARCHIVE" />
        <link rel="shortcut icon" href="image/favicon.ico" type="image/x-icon" />
	</head>
<body>
	<div class="center">

<h1>Редактирование таблицы на Python, JavaScript (на основе HTML 5, CSS 3.0)</h1>